function frame_sel = configSeqs


frame_sel = {
    struct('scene','S1','name','S1_G1','startFrame',1,'endFrame',6128,'topStart',1),...
    struct('scene','S1','name','S1_G2','startFrame',1,'endFrame',6128,'topStart',1),...
    struct('scene','S1','name','S1_G3','startFrame',1,'endFrame',6128,'topStart',1),...
    struct('scene','S2','name','S2_G1','startFrame',1,'endFrame',8491,'topStart',1),...
    struct('scene','S2','name','S2_G2','startFrame',1,'endFrame',8491,'topStart',1),...
    struct('scene','S2','name','S2_G3','startFrame',1,'endFrame',8491,'topStart',1),...
    struct('scene','S3','name','S3_G1','startFrame',1,'endFrame',7509,'topStart',1),...
    struct('scene','S3','name','S3_G2','startFrame',1,'endFrame',7509,'topStart',1),...
    struct('scene','S3','name','S3_G3','startFrame',1,'endFrame',7509,'topStart',1),...
%     struct('name','V0-S4-G_1','startFrame',1,'endFrame',2545,'topStart',1),...
%     struct('name','V0-S4-G_2','startFrame',1,'endFrame',2545,'topStart',1),...
%     struct('name','V0-S4-G_3','startFrame',1,'endFrame',2545,'topStart',1)
};
